### ISSUE TITLE
Issue in ESPIDf

### ISSUE THREAD

**Issue by JacobEPTechnologies421** [Rupakpoddar/FirebaseArduino#2]
hi,

im using esp idf 5.1.4 and when i built i face this issue>

undefined reference to `Firebase::Firebase(String, String)'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by Rupakpoddar** [comment]
Hi @JacobEPTechnologies421,

It appears that you're encountering an issue related to using the Firebase instance in a locked mode. This error may result from including multiple Firebase libraries in your project, leading the program to reference the wrong Firebase class. To resolve this, please ensure that only one Firebase library is used in your code and remove any unused Firebase libraries from your machine.

If the issue persists, could you please share the specific code or a code snippet that triggers the error, along with all relevant header files included in your project? This will help me provide more accurate assistance.

Thank you!

**Comment by JacobEPTechnologies421** [comment]
Hi Thanks for the response.

In the IDF Im just using the FirebaseArduino and previously I used your ESP32Firebase, that was having some issues with NetworkServer in between ;)

I checked on both lock and test mode and intialized the REF URL and AUTH in my file-- sharing the code below,

#include <stdio.h>
#include "Arduino.h"
#include "Wifi.h"
#include "Firebase.h"
#include "secrets.h"

#define WIFI_SSID     "Jacob's S23 FE"
#define WIFI_PASSWORD "helloworld"
#define REFERENCE_URL "..."
/* Uncomment the following line for Locked Mode (With Authentication) */
#define AUTH_TOKEN "...."

Firebase fb(REFERENCE_URL, AUTH_TOKEN);
int batteryCAN[8];
int motorCAN[8];

extern "C" void app_main(void)
{
    initArduino();
    Serial.println("Hello World");

    ///////////////////////////////////////////////
    Serial.begin(115200);
    #if !defined(ARDUINO_UNOWIFIR4)
        WiFi.mode(WIFI_STA);
    #else

    #endif
    WiFi.disconnect();
    delay(1000);

    /* Connect to WiFi */
    Serial.println();
    Serial.println();
    Serial.print("Connecting to: ");
    Serial.println(WIFI_SSID);
    WiFi.begin(WIFI_SSID, WIFI_PASSWORD);

    while (WiFi.status() != WL_CONNECTED) {
        Serial.print("-");
        delay(500);
    }

    Serial.println();
    Serial.println("WiFi Connected");
    Serial.println();
    ///////////////////////////////////////////////

}

**Comment by JacobEPTechnologies421** [comment]
lol found the issue--missed an "o" for arduino for the CMAKE. build made successfully.
